export const paymentsData = [
  {
    id: 1,
    title: 'ARENA sales',
    requestedBy: 'Sourav',
    purpose: 'Purpose Test',
    date: '14 May 2026',
    time: '12:52 PM',
    rupees: 2,
    status: 'Success',
  },
  {
    id: 2,
    title: 'Swift Dzire Service',
    requestedBy: 'Rahul',
    purpose: 'Vehicle Maintenance',
    date: '16 May 2026',
    time: '10:30 AM',
    rupees: 4500,
    status: 'Expired',
  },
  {
    id: 3,
    title: 'Insurance Payment',
    requestedBy: 'Aman',
    purpose: 'Insurance Renewal',
    date: '18 May 2026',
    time: '03:15 PM',
    rupees: 12000,
    status: 'Success',
  },
  {
    id: 4,
    title: 'Fuel Expense',
    requestedBy: 'Karthik',
    purpose: 'Diesel Payment',
    date: '19 May 2026',
    time: '08:45 AM',
    rupees: 3200,
    status: 'Expired',
  },
  {
    id: 5,
    title: 'Car Accessories',
    requestedBy: 'Vikram',
    purpose: 'Seat Cover Purchase',
    date: '20 May 2026',
    time: '06:20 PM',
    rupees: 1850,
    status: 'Expired',
  },
  {
    id: 6,
    title: 'ARENA Booking',
    requestedBy: 'Naveen',
    purpose: 'Booking Advance',
    date: '22 May 2026',
    time: '11:10 AM',
    rupees: 25000,
    status: 'Success',
  },
  {
    id: 7,
    title: 'Vehicle Loan EMI',
    requestedBy: 'Harish',
    purpose: 'Monthly EMI',
    date: '23 May 2026',
    time: '09:00 AM',
    rupees: 18500,
    status: 'Success',
  },
  {
    id: 8,
    title: 'Showroom Expense',
    requestedBy: 'Deepak',
    purpose: 'Office Interior',
    date: '24 May 2026',
    time: '04:40 PM',
    rupees: 7800,
    status: 'Expired',
  },
  {
    id: 9,
    title: 'Test Drive Fuel',
    requestedBy: 'Ramesh',
    purpose: 'Fuel Refill',
    date: '25 May 2026',
    time: '01:25 PM',
    rupees: 2300,
    status: 'Expired',
  },
  {
    id: 10,
    title: 'Customer Refund',
    requestedBy: 'Ankit',
    purpose: 'Booking Cancellation',
    date: '26 May 2026',
    time: '05:55 PM',
    rupees: 15000,
    status: 'Success',
  },
];